# https://travis-ci.org

language: cpp

os: linux
dist: xenial

addons:
  apt:
    update: true
    packages:
      - ant
      - aria2
      - build-essential
      - cmake
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libsdl2-dev
      - pv
      - software-properties-common
    sources:
      - sourceline: 'ppa:zoogie/sdl2-snapshots'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:ubuntu-sdk-team/ppa'
  homebrew:
    update: true
    packages:
      - ccache
      - sdl2

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/clcache

# By encrypting the channel name, we disable notifications from forks by default.
# It's not actually a big secret.
notifications:
  irc:
    channels:
      - secure: "anmDihJ1uPnDSNDsEe3WQ5o4BsPApJbw6NupsAebt6kBxJm7WYKrSyUVmu/9GXgFvy756HBDVA6eikPtcak1+jLFfyOZqGw3ei69ZNnA+R7aoAzfiXilFqf53Yy2tzydEnF2nBYhJjQZgMBZUVWUD6pdKSXtVg/VZRhVqiDlb+A="
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository_slug}:%{branch} - %{message} %{build_url}"

jobs:
  include:
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Linux
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Android
           APP_ABI=arm64-v8a
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Android
           APP_ABI=armeabi-v7a
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Android
           APP_ABI=x86
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Android
           APP_ABI=x86_64
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Android
           APP_ABI=arm64-v8a
           LIBRETRO=TRUE
    - os: linux
      compiler: "clang"
      env: PPSSPP_BUILD_TYPE=Linux
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Linux
           QT=TRUE
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Linux
           LIBRETRO=TRUE
    - os: linux
      compiler: "clang"
      env: PPSSPP_BUILD_TYPE=Linux
           LIBRETRO=TRUE
    - os: osx
      osx_image: xcode9.4
      compiler: "clang"
      env: PPSSPP_BUILD_TYPE=macOS
    - os: osx
      osx_image: xcode9.4
      compiler: "clang"
      env: PPSSPP_BUILD_TYPE=iOS
    - os: windows
      compiler: "msvc2017"
      env: PPSSPP_BUILD_TYPE=Windows
    - os: windows
      compiler: "msvc2017"
      env: PPSSPP_BUILD_TYPE=Windows
           UWP=TRUE

before_install:
  - travis_retry bash .travis.sh travis_before_install

install:
  - travis_retry bash .travis.sh travis_install

script:
  - bash .travis.sh travis_script

after_success:
  - bash .travis.sh travis_after_success
